# Generated by Django 3.0.8 on 2020-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_chat_log',
            name='message_img',
            field=models.ImageField(blank=True, null=True, upload_to='101_messages'),
        ),
        migrations.AlterField(
            model_name='group_chat_log',
            name='message_img',
            field=models.ImageField(blank=True, null=True, upload_to='group_messages'),
        ),
    ]
