# Generated by Django 3.0.8 on 2020-10-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_friend_chat_log_messsage_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_chat_log',
            name='messsage_img_url',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
