# Generated by Django 3.0.8 on 2020-10-21 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0004_group_chat_log_messsage_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_chat_participants',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
