# Generated by Django 3.0.8 on 2020-11-02 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0006_auto_20201027_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Messenger.Group_Chat_Ledger'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
